name: help_scout
description: Help scout mobile SDK flutter implementation
version: 0.0.1
homepage: https://github.com/joeeasy/beacon

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.help_scout
        pluginClass: HelpScoutPlugin
      ios:
        pluginClass: HelpScoutPlugin